### ISSUE TITLE
TypeError: Zone.assertZonePatched is not a function

### ISSUE THREAD

**Issue by mquentin** [vladotesanovic/angular2-express-starter#24]
Hello,

I have just updated my package.json according to your new "Angular 2 final release" version. I do have the zone.js version 0.6.23 but I get a Zone.assertZonePatched is not a function typeError. Do you have any clue about this new error ?

Regards,
Maxime

**Comment by vladotesanovic** [comment]
Yep,

you need to copy zone.js or zone.min.js from node_modules to public/assets/js/vendor

**Comment by mquentin** [comment]
Thanks !!

**Comment by XerO00** [comment]
@vladotesanovic  can u please explain more not able to understand which folder u referring to by giving  public/assets/js/vendor  path

**Comment by vladotesanovic** [comment]
@XerO00 
What problems you have, this is very old issue.

**Comment by XerO00** [comment]
@vladotesanovic 
I am having problem with my angular 2 app while loading due to my zone.js.. whereas I have 0.8.20
Version and not able to implement this correctly into my app.. can you please suggest latest version and correct way to implementing it to project.

Also  I have problem with my typescript running on version "^2.8.0-dev.20180308" and problem is I have to convert my example.ts file into example.js by typing command into cmd manually... Can you please suggest how to make typescript work automatically to do conversion of example.ts file into example.js

Added all the files used in my project are pasted here https://github.com/angular/quickstart/issues/384

Thanks in advance!! Please let me know if any help needed.
