### ISSUE TITLE
Production usecase

### ISSUE THREAD

**Issue by danrevah** [vladotesanovic/angular2-express-starter#46]
I saw in the instructions that you are instructing to deploy only the `dist` folder.
How do you manage to serve that static `index.html` without angular-cli?
any suggestions?

**Comment by vladotesanovic** [comment]
If you deploy your dist folder somewhere to server, let say that path to dist folder is:

```/home/app_user/your_app/dist``` 

You can run your application with:

- plain node
- [pm2](https://github.com/Unitech/pm2)
- [forever]( https://github.com/foreverjs/forever)

We will use **forever**.

First thing is to install it globally: ``` [sudo] npm install forever -g ```

than start your application with: 

```
cd /home/app_user/your_app/dist
PORT=80 forever start /server/bin/www.js
```

Note that we put PORT before forever command, that is because we read PORT value from env.

Right now you can access your page with: **http://your.host**

If you use NGINX within node/express your need to configure NGINX to proxy to your app. Your port need to be something different than 80, because NGINX use 80 in this case.

```
server {
        
        listen 80;

	# custom error page
	error_page 404 /404.html;
	location = /404.html {
		root /home/app_user/pages/error;
		internal;
	}
	error_page 500 502 503 504 /500.html;
	location = /500.html {
                root /home/app_user/pages/error;
                internal;
        }

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	location / {
		proxy_pass http://localhost:8080;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	}
}
```

**Comment by danrevah** [comment]
@vladotesanovic  Thanks that was very helpful!
