### ISSUE TITLE
ng serve deletes /dist directory

### ISSUE THREAD

**Issue by luke88jones** [vladotesanovic/angular2-express-starter#73]
Hello, 

I believe there is an issue with the current configuration when running `npm run start`. A recent change to `ng serve` made it delete the `./dist` directory. This is now causing the server to fail to start as its failing to locate the `www.js` file.

![image](https://cloud.githubusercontent.com/assets/1705416/25739785/50f87682-317b-11e7-8312-de983ac791a7.png)

This is occurring on Windows

**Comment by stephenlane** [comment]
I get similar issue, just keep running the npm run start command and it will eventually work :)

**Comment by avbentem** [comment]
Just for future reference: deleting the `dist` folder is done since Angular CLI's https://github.com/angular/angular-cli/pull/4293

**Comment by avbentem** [comment]
It seems that just changing the order in `concurrently` indeed lowers the chances of this happening, but does not always fix it. 

However, [since 1.1.0-rc.0 `ng serve` also supports `--delete-output-path=false`](https://github.com/angular/angular-cli/issues/4366#issuecomment-302539322), which suppresses deletion of `dist`:

    "start": "concurrently --kill-others \"ng serve --delete-output-path=false --aot=true --progress=false --proxy-config proxy.conf.json\" \"npm run _server:run\""

Alternatively, to get some implicit documentation, one could use some verbose `--output-path=dummy-to-preserve-dist-folder` on the command line of `ng serve`, which will then delete the `./dummy-to-preserve-dist-folder` folder if that would exist, but above all leave `dist` alone.

Both tested on OS X.

As an aside, instead of calling `tsc` twice and using `concurrently` in:

    "_server:run": "tsc -p ./server && concurrently \"tsc -w -p ./server\" \"nodemon dist/server/bin/www.js\" "

...I am using https://www.npmjs.com/package/tsc-watch The above makes `tsc -w` always trigger yet another compilation, which makes `nodemon` log `[nodemon] restarting due to changes...` a few times upon starting. Using `tsc-watch` avoids that:

    "_server:run": "tsc-watch -p ./server --onSuccess \"nodemon dist/server/bin/www.js\""

(Thanks for a nice starter!)
